# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Petstore.Model.Pet do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"category",
    :"name",
    :"photoUrls",
    :"tags",
    :"status"
  ]
end

defimpl Poison.Decoder, for: Petstore.Model.Pet do
  import Petstore.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"category", :struct, Petstore.Model.Category, options)
    |> deserialize(:"tags", :list, Petstore.Model.Tag, options)
  end
end


